#!/usr/bin/env bash
# godot-interact: Simulate player input in Godot 4 scenes and capture results.
#
# Injects an autoload script that replays input actions (touch, drag, key, wait),
# then uses Godot's --write-movie to capture the rendered output. Extracts PNG
# frames with ffmpeg — same approach as godot-preview, but with input simulation.
#
# Requirements:
#   - Godot 4.x (tested with 4.4.1)
#   - ffmpeg
#
# Usage:
#   godot-interact <project_path> <scene_path> --actions <json_or_file> [options]
#
# Examples:
#   # Wait 2 seconds then tap center of screen
#   godot-interact ./my_game res://scenes/lobby.tscn \
#     --actions '{"actions":[{"type":"wait","seconds":2},{"type":"touch","position":[540,960]}]}'
#
#   # Drag from one point to another
#   godot-interact ./my_game res://scenes/lobby.tscn \
#     --actions '{"actions":[{"type":"wait","seconds":1},{"type":"drag","from":[540,960],"to":[200,960],"duration":0.5}]}'
#
#   # Load actions from a file
#   godot-interact ./my_game res://scenes/lobby.tscn --actions actions.json

set -euo pipefail

# --- Defaults ---
GODOT_BIN="${GODOT_BIN:-/Applications/Godot.app/Contents/MacOS/Godot}"
RESOLUTION="1080x1920"
FRAME="5"
FPS="2"
RENDER_SECONDS="15"
OUTPUT_DIR="/tmp/godot-interact"
OUTPUT_FILE=""
VERBOSE=false
ACTIONS_JSON=""
CAPTURE_FRAMES="last"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

usage() {
    cat <<'USAGE'
godot-interact — Simulate player input in Godot 4 scenes and capture results.

USAGE:
  godot-interact <project_path> <scene_path> --actions <json_or_file> [options]

ACTION FORMAT (JSON):
  {
    "actions": [
      {"type": "wait", "seconds": 2},
      {"type": "touch", "position": [540, 960]},
      {"type": "drag", "from": [540, 960], "to": [200, 960], "duration": 0.5},
      {"type": "key", "key": "ui_accept"},
      {"type": "key", "key": "ui_up", "duration": 1.0},
      {"type": "scroll", "position": [540, 960], "direction": "up", "amount": 3}
    ]
  }

ACTION TYPES:
  wait      Pause for N seconds before next action
  touch     Tap at viewport coordinates [x, y]
  drag      Touch-drag from [x, y] to [x, y] over duration seconds
  key       Press a Godot input action name (or scancode)
  scroll    Scroll wheel at position

OPTIONS:
  --actions, -a JSON|FILE   Actions JSON string or path to .json file (required)
  -r, --resolution WxH      Viewport resolution (default: 1080x1920)
  -f, --frame N[,N,...]     Frame number(s) to extract (default: last rendered)
  -s, --seconds N           Total render time (default: 15)
  --fps N                   Render FPS (default: 2)
  -o, --output PATH         Output PNG path
  -g, --godot PATH          Path to Godot binary
  --capture WHEN            When to capture: "last", "after-each", or frame numbers
  -v, --verbose             Show Godot output
  -h, --help                Show this help

ENVIRONMENT:
  GODOT_BIN                 Path to Godot binary

DESIGNED FOR AI AGENTS:
  This tool enables interactive visual iteration:

    1. Agent modifies scene/scripts
    2. Agent defines input actions (tap button, drag slider, etc.)
    3. Agent runs: godot-interact ./project res://scene.tscn --actions '{...}'
    4. Agent reads output PNG to SEE the result of the interaction
    5. Agent adjusts and repeats
USAGE
}

log() { echo -e "${CYAN}[godot-interact]${NC} $*"; }
warn() { echo -e "${YELLOW}[godot-interact]${NC} $*"; }
err() { echo -e "${RED}[godot-interact]${NC} $*" >&2; }
ok() { echo -e "${GREEN}[godot-interact]${NC} $*"; }

check_deps() {
    if ! command -v ffmpeg &>/dev/null; then
        err "ffmpeg not found. Install with: brew install ffmpeg"
        exit 1
    fi
    if [[ ! -x "$GODOT_BIN" ]] && ! command -v "$GODOT_BIN" &>/dev/null; then
        err "Godot not found at: $GODOT_BIN"
        err "Set GODOT_BIN or use --godot <path>"
        exit 1
    fi
}

scene_basename() {
    local scene="$1"
    basename "$scene" .tscn
}

# Generate the GDScript autoload that replays input actions
generate_replay_script() {
    local actions_json="$1"
    local output_path="$2"

    cat > "$output_path" <<'GDSCRIPT'
extends Node
# Auto-generated by godot-interact — replays input actions for capture.

var actions: Array = []
var current_action: int = 0
var action_timer: float = 0.0
var drag_progress: float = 0.0
var started: bool = false
var start_delay: float = 1.0  # Let scene settle before input

func _ready() -> void:
    var json_str := '__ACTIONS_PLACEHOLDER__'
    var json := JSON.new()
    var err := json.parse(json_str)
    if err != OK:
        push_error("godot-interact: Failed to parse actions JSON")
        return
    var data = json.get_data()
    if data is Dictionary and data.has("actions"):
        actions = data["actions"]
    print("[godot-interact] Loaded %d actions" % actions.size())

func _process(delta: float) -> void:
    if not started:
        start_delay -= delta
        if start_delay <= 0:
            started = true
        return

    if current_action >= actions.size():
        return

    var action: Dictionary = actions[current_action]
    var action_type: String = action.get("type", "")

    # Shared locals hoisted above match (Godot 4 match branches share scope)
    var pos: Array
    var dur: float
    var from: Array
    var to: Array
    var key_name: String
    var scroll_dir: String
    var scroll_amt: int
    var t: float
    var current_pos: Vector2

    match action_type:
        "wait":
            dur = action.get("seconds", 1.0)
            action_timer += delta
            if action_timer >= dur:
                _advance()
        "touch":
            pos = action.get("position", [0, 0])
            _simulate_touch(Vector2(pos[0], pos[1]))
            _advance()
        "drag":
            from = action.get("from", [0, 0])
            to = action.get("to", [0, 0])
            dur = action.get("duration", 0.5)
            drag_progress += delta
            t = clampf(drag_progress / dur, 0.0, 1.0)
            current_pos = Vector2(from[0], from[1]).lerp(Vector2(to[0], to[1]), t)
            if drag_progress == delta:
                # First frame: press
                _simulate_touch_press(current_pos)
            else:
                _simulate_touch_move(current_pos)
            if t >= 1.0:
                _simulate_touch_release(current_pos)
                _advance()
        "key":
            key_name = action.get("key", "")
            dur = action.get("duration", 0.0)
            if dur > 0:
                action_timer += delta
                _simulate_key_hold(key_name)
                if action_timer >= dur:
                    _simulate_key_release(key_name)
                    _advance()
            else:
                _simulate_key_press(key_name)
                _advance()
        "scroll":
            pos = action.get("position", [0, 0])
            scroll_dir = action.get("direction", "up")
            scroll_amt = action.get("amount", 3)
            _simulate_scroll(Vector2(pos[0], pos[1]), scroll_dir, scroll_amt)
            _advance()
        "joystick":
            var jx: float = action.get("dx", 0.0)
            var jy: float = action.get("dy", 0.0)
            dur = action.get("duration", 0.0)
            _set_joystick(Vector2(jx, jy))
            if dur > 0:
                action_timer += delta
                if action_timer >= dur:
                    _set_joystick(Vector2.ZERO)
                    _advance()
            else:
                _set_joystick(Vector2.ZERO)
                _advance()
        _:
            push_warning("godot-interact: Unknown action type: %s" % action_type)
            _advance()

func _advance() -> void:
    current_action += 1
    action_timer = 0.0
    drag_progress = 0.0
    if current_action < actions.size():
        print("[godot-interact] Action %d/%d: %s" % [current_action + 1, actions.size(), actions[current_action].get("type", "?")])
    else:
        print("[godot-interact] All actions complete")

func _simulate_touch(pos: Vector2) -> void:
    _simulate_touch_press(pos)
    # Release next frame via deferred
    _simulate_touch_release.call_deferred(pos)

func _simulate_touch_press(pos: Vector2) -> void:
    var event := InputEventScreenTouch.new()
    event.position = pos
    event.pressed = true
    event.index = 0
    Input.parse_input_event(event)

func _simulate_touch_move(pos: Vector2) -> void:
    var event := InputEventScreenDrag.new()
    event.position = pos
    event.index = 0
    Input.parse_input_event(event)

func _simulate_touch_release(pos: Vector2) -> void:
    var event := InputEventScreenTouch.new()
    event.position = pos
    event.pressed = false
    event.index = 0
    Input.parse_input_event(event)

## Map WASD → Godot built-in actions (most reliable for action_press/release).
const _ACTION_MAP := {
    "W": "ui_up", "S": "ui_down", "A": "ui_left", "D": "ui_right",
}

## Map other key names → Godot KEY_* constants (fallback for non-WASD).
const _KEY_MAP := {
    "SPACE": KEY_SPACE, "SHIFT": KEY_SHIFT, "ENTER": KEY_ENTER,
    "UP": KEY_UP, "DOWN": KEY_DOWN, "LEFT": KEY_LEFT, "RIGHT": KEY_RIGHT,
    "E": KEY_E, "Q": KEY_Q, "F": KEY_F, "R": KEY_R,
    "1": KEY_1, "2": KEY_2, "3": KEY_3, "4": KEY_4,
}

## Split combined keys ("W+A") and press each.
func _simulate_key_press(key_str: String) -> void:
    for part in key_str.split("+"):
        var k := part.strip_edges().to_upper()
        if _ACTION_MAP.has(k):
            Input.action_press(_ACTION_MAP[k])
            Input.action_release.call_deferred(_ACTION_MAP[k])
        elif _KEY_MAP.has(k):
            var ev := InputEventKey.new()
            ev.keycode = _KEY_MAP[k]
            ev.pressed = true
            Input.parse_input_event(ev)
            var rel := InputEventKey.new()
            rel.keycode = _KEY_MAP[k]
            rel.pressed = false
            Input.parse_input_event.call_deferred(rel)

func _simulate_key_hold(key_str: String) -> void:
    for part in key_str.split("+"):
        var k := part.strip_edges().to_upper()
        if _ACTION_MAP.has(k):
            Input.action_press(_ACTION_MAP[k])
        elif _KEY_MAP.has(k):
            var ev := InputEventKey.new()
            ev.keycode = _KEY_MAP[k]
            ev.pressed = true
            Input.parse_input_event(ev)

func _simulate_key_release(key_str: String) -> void:
    for part in key_str.split("+"):
        var k := part.strip_edges().to_upper()
        if _ACTION_MAP.has(k):
            Input.action_release(_ACTION_MAP[k])
        elif _KEY_MAP.has(k):
            var ev := InputEventKey.new()
            ev.keycode = _KEY_MAP[k]
            ev.pressed = false
            Input.parse_input_event(ev)

func _set_joystick(input: Vector2) -> void:
    var players := get_tree().get_nodes_in_group("player")
    if players.size() > 0 and players[0].has_method("set_joystick_input"):
        players[0].set_joystick_input(input)

func _simulate_scroll(pos: Vector2, direction: String, amount: int) -> void:
    for i in amount:
        var event := InputEventMouseButton.new()
        event.position = pos
        event.global_position = pos
        match direction:
            "up": event.button_index = MOUSE_BUTTON_WHEEL_UP
            "down": event.button_index = MOUSE_BUTTON_WHEEL_DOWN
            "left": event.button_index = MOUSE_BUTTON_WHEEL_LEFT
            "right": event.button_index = MOUSE_BUTTON_WHEEL_RIGHT
        event.pressed = true
        Input.parse_input_event(event)
GDSCRIPT

    # Replace placeholder with actual JSON.
    # The template uses single-quoted GDScript string ('...') so double
    # quotes in JSON don't need escaping.  Only backslashes need doubling
    # and the sed delimiter (|) needs escaping (JSON won't contain either).
    local escaped_json
    escaped_json=$(printf '%s' "$actions_json" | sed 's/\\/\\\\/g; s/|/\\|/g')

    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "s|__ACTIONS_PLACEHOLDER__|${escaped_json}|" "$output_path"
    else
        sed -i "s|__ACTIONS_PLACEHOLDER__|${escaped_json}|" "$output_path"
    fi
}

main() {
    local project_path=""
    local scene_path=""

    # Parse positional args
    if [[ $# -lt 2 ]]; then
        usage
        exit 1
    fi
    project_path="$1"; shift
    scene_path="$1"; shift

    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -a|--actions) ACTIONS_JSON="$2"; shift 2 ;;
            -r|--resolution) RESOLUTION="$2"; shift 2 ;;
            -f|--frame) FRAME="$2"; shift 2 ;;
            -s|--seconds) RENDER_SECONDS="$2"; shift 2 ;;
            --fps) FPS="$2"; shift 2 ;;
            -o|--output) OUTPUT_FILE="$2"; shift 2 ;;
            -g|--godot) GODOT_BIN="$2"; shift 2 ;;
            --capture) CAPTURE_FRAMES="$2"; shift 2 ;;
            -v|--verbose) VERBOSE=true; shift ;;
            -h|--help) usage; exit 0 ;;
            *) err "Unknown option: $1"; exit 1 ;;
        esac
    done

    if [[ -z "$ACTIONS_JSON" ]]; then
        err "Actions required. Use --actions '<json>' or --actions <file.json>"
        exit 1
    fi

    check_deps

    # Load actions from file if it's a path
    if [[ -f "$ACTIONS_JSON" ]]; then
        ACTIONS_JSON="$(cat "$ACTIONS_JSON")"
    fi

    # Resolve project path
    project_path="$(cd "$project_path" && pwd)"
    if [[ ! -f "$project_path/project.godot" ]]; then
        err "No project.godot found in: $project_path"
        exit 1
    fi

    # Setup output
    mkdir -p "$OUTPUT_DIR"
    local scene_name
    scene_name="$(scene_basename "$scene_path")"
    local avi_path="$OUTPUT_DIR/${scene_name}_interact.avi"
    local log_path="$OUTPUT_DIR/${scene_name}_godot.log"
    local replay_script="$OUTPUT_DIR/_interact_replay.gd"

    if [[ -z "$OUTPUT_FILE" ]]; then
        OUTPUT_FILE="$OUTPUT_DIR/${scene_name}_interact.png"
    fi

    # Generate replay script
    log "Generating input replay script..."
    generate_replay_script "$ACTIONS_JSON" "$replay_script"

    # Backup project.godot to restore after
    local project_godot="$project_path/project.godot"
    local project_backup="$OUTPUT_DIR/_project.godot.bak"
    cp "$project_godot" "$project_backup"

    # Copy replay script into project
    local replay_dest="$project_path/_interact_replay.gd"
    cp "$replay_script" "$replay_dest"

    # Add autoload to project.godot
    # We need to add it as the last autoload
    if ! grep -q "_interact_replay" "$project_godot"; then
        # Find the [autoload] section and append our autoload
        if grep -q "^\[autoload\]" "$project_godot"; then
            # Add after the last autoload entry (before next section)
            local last_autoload_line
            last_autoload_line=$(grep -n "^[A-Za-z_]" "$project_godot" | grep -A1 "autoload" | tail -1 | cut -d: -f1)

            # Simpler approach: just append to [autoload] section
            sed_cmd='s/^\[autoload\]/[autoload]\n_InteractReplay="*res:\/\/_interact_replay.gd"/'
            if [[ "$(uname)" == "Darwin" ]]; then
                sed -i '' "s|^\[autoload\]|[autoload]\\
_InteractReplay=\"*res://_interact_replay.gd\"|" "$project_godot"
            else
                sed -i "s|^\[autoload\]|[autoload]\n_InteractReplay=\"*res://_interact_replay.gd\"|" "$project_godot"
            fi
        else
            # No autoload section exists — add one
            echo -e "\n[autoload]\n_InteractReplay=\"*res://_interact_replay.gd\"" >> "$project_godot"
        fi
    fi

    log "Rendering ${scene_path} with ${#ACTIONS_JSON} bytes of actions..."

    # Clean previous capture
    rm -f "$avi_path"

    # Launch Godot
    "$GODOT_BIN" \
        --path "$project_path" \
        --resolution "$RESOLUTION" \
        --windowed \
        --write-movie "$avi_path" \
        --fixed-fps "$FPS" \
        "$scene_path" \
        &>"$log_path" &
    local godot_pid=$!

    # Wait for render duration then kill
    sleep "$RENDER_SECONDS"
    kill "$godot_pid" 2>/dev/null || true
    wait "$godot_pid" 2>/dev/null || true
    sleep 1

    # Restore project.godot and clean up
    cp "$project_backup" "$project_godot"
    rm -f "$replay_dest"
    rm -f "$project_path/_interact_replay.gd.uid" 2>/dev/null
    rm -f "$replay_script"
    rm -f "$project_backup"

    # Check if AVI was created
    if [[ ! -f "$avi_path" ]]; then
        err "Godot failed to produce output. Check log: $log_path"
        if $VERBOSE; then
            cat "$log_path"
        fi
        exit 1
    fi

    # Check for script errors
    local error_count
    error_count="$(grep -c "SCRIPT ERROR" "$log_path" 2>/dev/null || true)"
    error_count="${error_count:-0}"
    if [[ "$error_count" -gt 0 ]] 2>/dev/null; then
        warn "$error_count script error(s) detected — check $log_path"
    fi

    # Determine which frame to extract
    if [[ "$CAPTURE_FRAMES" == "last" ]]; then
        # Get total frame count and use the last one
        local total_frames
        total_frames=$(ffprobe -v error -count_frames -select_streams v:0 \
            -show_entries stream=nb_read_frames -of csv=p=0 "$avi_path" 2>/dev/null || echo "0")
        total_frames="${total_frames:-0}"
        if [[ "$total_frames" -gt 1 ]]; then
            FRAME=$((total_frames - 1))
        else
            FRAME=0
        fi
        log "Total frames: $total_frames, extracting frame $FRAME"
    fi

    # Extract frame(s)
    IFS=',' read -ra FRAMES <<< "$FRAME"
    local extracted=0

    for frame_num in "${FRAMES[@]}"; do
        local out_path
        if [[ ${#FRAMES[@]} -gt 1 ]]; then
            out_path="${OUTPUT_FILE%.png}_f${frame_num}.png"
        else
            out_path="$OUTPUT_FILE"
        fi

        if ffmpeg -i "$avi_path" \
            -vf "select=eq(n\\,${frame_num})" \
            -vframes 1 -update 1 \
            "$out_path" -y \
            &>/dev/null; then
            ok "Frame ${frame_num} → ${out_path}"
            ((extracted++))
        else
            warn "Failed to extract frame ${frame_num}"
        fi
    done

    # Clean up AVI
    rm -f "$avi_path"

    if [[ $extracted -eq 0 ]]; then
        err "No frames extracted. Try increasing --seconds."
        exit 1
    fi

    # Print path for AI agent consumption
    if [[ ${#FRAMES[@]} -eq 1 ]]; then
        echo "$OUTPUT_FILE"
    fi
}

# --- Entry ---
case "${1:-help}" in
    help|-h|--help) usage ;;
    *) main "$@" ;;
esac
